name: Comment PR
on: pull_request
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Comment on PR
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "Hello, ${GITHUB_ACTOR}! This is a comment from the GitHub Actions workflow."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
