name: Manual
on:
  push:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Output 1
        run: echo "This is executed by a manual workflow and a push event"

      - name: Output 2
        # ワークフローを手動で実行する場合は実行されない
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: echo "This is executed only by a push event"
